name: Error Report
description: Report an error on PscyhWiki!
labels: [error]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your error here."
    validations:
      required: true

  - type: textarea
    id: body-markdown
    attributes:
      label: "The wiki function which you found the error"
    validations:
      required: false